service: single-page-app-via-cloudfront7

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  s3Bucket: wwwwwwwwwwwwwww7

provider:
  name: aws
  runtime: nodejs4.3

resources:
  Resources:
    WebAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${self:custom.s3Bucket}.s3.amazonaws.com
              # An identifier for the origin which must be unique within the distribution
              Id: WebApp
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
              # In case you want to restrict the bucket access use S3OriginConfig and remove CustomOriginConfig
              # S3OriginConfig:
              #   OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
          Enabled: 'true'
          DefaultRootObject: index.html
          # Logging:
          #   IncludeCookies: 'false'
          #   Bucket: mylogs.s3.amazonaws.com
          #   Prefix: myprefix
          # Aliases:
          # - mysite.example.com
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            # The origin id defined above
            TargetOriginId: WebApp
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                # cookies to forward to the origin of the cache behavior. You can specify none, all, or whitelist
                Forward: none
            ViewerProtocolPolicy: allow-all
          # The certificate to use when viewers use HTTPS to request objects.
          # ViewerCertificate:
          #   CloudFrontDefaultCertificate: 'true'
    WebAppS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3Bucket}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: WebAppS3Bucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.s3Bucket}/*
